#swagger:
#  title: 维利博客系统接口文档
#  description: 维利博客系统-后端管理
#  exclude-path: /error # 剔除请求
#
#server:
#  port: 8003
#  servlet:
#    context-path: /system  # 上下文件路径，请求前缀 ip:port/system
#
#spring:
#  application:
#    name: system-server # 应用名
#  # 数据源配置
#  datasource:
#    username: root
#    password: 1qaz2wsx!
#    url: jdbc:mysql://127.0.0.1:3306/mxg_blog_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#    #mysql8版本以上驱动包指定新的驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
#    initialSize: 8
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848   #nacos服务
#
#mybatis-plus:
#  type-aliases-package: com.cherry.blog.entities
#  # xxxMapper.xml 路径
#  mapper-locations: classpath*:com/cherry/blog/system/mapper/**/*.xml
#
## 日志级别，会打印sql语句
#logging:
#  level:
#    com.cherry.blog.system.mapper: debug
#
##阿里云OSS配置
#weili:
#  blog:
#    # 阿里云配置
#    aliyun:
#      endpoint: http://oss-cn-beijing.aliyuncs.com # OSS 端点，根据自己地域替换
#      accessKeyId: LTAI5tCBHXBfW1FuNwSAG4hZ # 根据自己的配置
#      accessKeySecret: QW517Vbo21mAIppKlb0ynRBLfOPLPT # 根据自己的配置
#      bucketName: weiliblog # 存储空间名称
#      # Bucket域名，访问文件时作为URL前缀，注意前面加上 https 和结尾加上 /
#      bucketDomain: https://weiliblog.oss-cn-beijing.aliyuncs.com/